name: Update Windows DLL

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_dll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Get latest release URL
        id: get_release_url
        run: |
          latest_release_url=$(curl -s https://api.github.com/repos/shinchiro/mpv-winbuild-cmake/releases/latest | jq -r '.assets[].browser_download_url' | grep mpv-dev-x86_64-2 | head -n 1)
          echo "url=$latest_release_url" >> "$GITHUB_OUTPUT"

      - name: Download archive
        run: wget "${{ steps.get_release_url.outputs.url }}"

      - name: Calculate MD5 hash
        id: calculate_md5
        run: |
          md5sum mpv-dev-x86_64-2*.7z | awk '{print $1}' > md5.txt
          echo "md5=$(cat md5.txt)" >> "$GITHUB_OUTPUT"

      - name: Update CMakeLists.txt
        run: |
          cd libs/windows/media_kit_libs_windows_video/windows
          FILENAME=$(basename "${{ steps.get_release_url.outputs.url }}")
          sed -i "s#LIBMPV \".*\"#LIBMPV \"$FILENAME\"#g" CMakeLists.txt
          sed -i "s#LIBMPV_URL \".*\"#LIBMPV_URL \"${{ steps.get_release_url.outputs.url }}\"#g" CMakeLists.txt
          sed -i "s/LIBMPV_MD5 \".*\"/LIBMPV_MD5 \"${{ steps.calculate_md5.outputs.md5 }}\"/g" CMakeLists.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt
          if git diff --cached --quiet; then
            echo "No DLL hash change"
            exit 0
          fi
          git commit -m "Update DLL hash"
          git push
